name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Correr tests
      - name: Run tests
        run: npm test

      # 5. Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build de la imagen Docker
      - name: Build Docker image
        run: docker build -t willian28/hola-mundo-app:latest .

      # 7. Push de la imagen Docker
      - name: Push Docker image
        run: docker push willian28/hola-mundo-app:latest
